name: black

on:
  push:
    branches: ["main", "dev/ijoc_paper"]
  pull_request:
    branches: ["main", "dev/ijoc_paper"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
