name: black
on:
  push:
    branches: [ "techno_paper"]
  pull_request:
    branches: [ "techno_paper"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable