name: CI Papers

on:
  push:
    branches: [ "dev/PUQ_with_hetGPy"]
  pull_request:
    branches: [ "dev/PUQ_with_hetGPy"]

jobs:
  run-full-tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install -e . --use-pep517
    - name: Test with pytest on main branch (an example from Technometrics paper)
      if: github.ref == 'refs/heads/dev/PUQ_with_hetGPy'
      run: |
        python ./examples/Example1/example.py
     
